[tool.poetry]
name = "poetry-for-container"
version = "0.1.0"
description = "poetry will be used to update the container dependencies"
authors = ["groep 3 EAI2"]

[tool.poetry.dependencies]
requests = "*"

