name: All
on:
  issues:
    types:
      - reopened
      - opened
      - assigned
      - unassigned
  issue_comment:
    types:
      - created

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        run: |
          # Check if the issue is not assigned
          if [ -z "${{ github.event.issue.assignee }}" ]; then
            gh issue edit "${{ github.event.issue.number }}" --add-label "to do"
            gh issue edit "${{ github.event.issue.number }}" --remove-label "in progress"
          else
            gh issue edit "${{ github.event.issue.number }}" --remove-label "to do"
            gh issue edit "${{ github.event.issue.number }}" --add-label "in progress"
          fi

          # Check if the comment contains "help wanted"
          if [[ "${{ github.event_name }}" == "issue_comment" && "${{ github.event.comment.body }}" == *"help wanted"* ]]; then
            gh issue edit "${{ github.event.issue.number }}" --add-label "help wanted"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: to do, in progress, help wanted

  label_existing_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label existing issues
        run: |
          # Iterate through all existing issues
          for issue_number in $(gh issue list --json "number" -L 100 --repo ${{ github.repository }} | jq -r '.[].number'); do
            # Apply your labeling logic here for existing issues
            # Check if the issue is not assigned
            if [ -z "$(gh issue view $issue_number --json "assignee.login" -q '.assignee.login')" ]; then
              gh issue edit $issue_number --add-label "to do"
              gh issue edit $issue_number --remove-label "in progress"
            else
              gh issue edit $issue_number --remove-label "to do"
              gh issue edit $issue_number --add-label "in progress"
            fi

          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: to do, in progress, help wanted
