name: All

on:
  issues:
    types:
      - reopened
      - opened
      - assigned
      - unassigned
  issue_comment:
    types:
      - created

jobs:

  label_existing_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label existing issues
        run: |

          for issue_number in $(gh issue list --json "number" -L 100 --repo ${{ github.repository }} | jq -r '.[].number'); do
            if [ -z "$(gh issue view $issue_number --json "assignee.login" -q '.assignee.login')" ]; then
              gh issue edit $issue_number --add-label "in progress"
              gh issue edit $issue_number --remove-label "in progress"
            else
              gh issue edit $issue_number --remove-label "to do"
              gh issue edit $issue_number --add-label "in progress"
            fi

          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: to do, in progress, help wanted
