name: todo

on:
  issues:
    types:
      - reopened
      - opened
      - assigned
      - unassigned
  issue_comment:
    types:
      - created

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        run: |
          # Check if the issue is not assigned
          if [ -z "${{ github.event.issue.assignee }}" ]; then
            gh issue edit "${{ github.event.issue.number }}" --add-label "to do"
            gh issue edit "${{ github.event.issue.number }}" --remove-label "in progress"
          else
            gh issue edit "${{ github.event.issue.number }}" --remove-label "to do"
            gh issue edit "${{ github.event.issue.number }}" --add-label "in progress"
          fi
          # Check if the comment contains "help wanted"
          if [[ "${{ github.event_name }}" == "issue_comment" && "${{ github.event.comment.body }}" == *"help wanted"* ]]; then
            gh issue edit "${{ github.event.issue.number }}" --add-label "help wanted"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: to do, in progress, help wanted
